# Generated by Django 6.0.5 on 2026-06-08 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_options_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='blog/hero-bg.jpg', upload_to='blog/'),
        ),
    ]
